import { useId, useState, type FormEvent, type ReactNode } from 'react'
import { ArrowDownToLine, LoaderCircle, Trash2 } from 'lucide-react'
import { GlassEffect } from '@/components/ui/liquid-glass'
import { goTo } from '@/lib/navigate'
import { AccountRequestError, sendJson, type Preferences } from '@/lib/account'

const CONFIRM_WORD = 'DELETE'
const EXPORT_FALLBACK_NAME = 'echotrace-account-export.json'

type Props = {
  preferences: Preferences | null
  onPreferencesChange: (preferences: Preferences) => void
  onRecordingsDeleted: () => void
}

type PreferenceKey = keyof Preferences
type SelectOption = { value: string; label: string }

function PreferenceSelect({ id, label, help, value, options, busy, error, onChange }: {
  id: PreferenceKey; label: string; help: string; value: string; options: SelectOption[]; busy: boolean; error?: string; onChange: (value: string) => void
}) {
  return <div className="account-preference">
    <label className="case-field" htmlFor={`pref-${id}`}>{label}
      <select id={`pref-${id}`} value={value} disabled={busy} aria-describedby={`pref-${id}-note`} onChange={event => onChange(event.target.value)}>
        {options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}
      </select>
    </label>
    <p id={`pref-${id}-note`} className={error ? 'account-error' : 'case-help'} role={error ? 'alert' : undefined}>{busy ? 'Saving…' : error || help}</p>
  </div>
}

function TypedConfirm({ title, description, buttonLabel, busyLabel, onConfirm }: {
  title: string; description: ReactNode; buttonLabel: string; busyLabel: string; onConfirm: () => Promise<string | void>
}) {
  const inputId = useId()
  const [typed, setTyped] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const confirmed = typed === CONFIRM_WORD

  async function submit(event: FormEvent) {
    event.preventDefault()
    if (!confirmed) { setError(`Type ${CONFIRM_WORD} in capital letters to confirm.`); return }
    setBusy(true); setError(''); setMessage('')
    try { setMessage((await onConfirm()) || ''); setTyped('') }
    catch (caught) { setError((caught as Error).message) }
    finally { setBusy(false) }
  }

  return <form className="account-form account-confirm" onSubmit={submit} noValidate>
    <h3>{title}</h3>
    <p className="case-help">{description}</p>
    <label className="case-field" htmlFor={inputId}>Type {CONFIRM_WORD} to confirm
      <input id={inputId} value={typed} autoComplete="off" spellCheck={false} disabled={busy} onChange={event => { setTyped(event.target.value); setError('') }} />
    </label>
    <div className="account-form-footer">
      <p className={error ? 'account-error' : 'account-status'} role={error ? 'alert' : 'status'}>{error || message}</p>
      <button type="submit" className="outline-button account-danger-button" disabled={busy || !confirmed}>{busy ? <LoaderCircle size={15} className="spin" /> : <Trash2 size={15} />}{busy ? busyLabel : buttonLabel}</button>
    </div>
  </form>
}

function exportFilename(disposition: string | null) {
  const match = disposition?.match(/filename\*?=(?:UTF-8'')?"?([^";]+)"?/i)
  return match ? decodeURIComponent(match[1]) : EXPORT_FALLBACK_NAME
}

function DownloadData() {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [done, setDone] = useState(false)

  async function download() {
    setBusy(true); setError(''); setDone(false)
    try {
      const response = await fetch('/api/account/export')
      if (!response.ok) {
        const body = await response.json().catch(() => null)
        throw new AccountRequestError(typeof body?.detail === 'string' ? body.detail : `Export failed (${response.status}).`, response.status)
      }
      const url = URL.createObjectURL(await response.blob())
      const link = document.createElement('a')
      link.href = url; link.download = exportFilename(response.headers.get('Content-Disposition')); link.click()
      setTimeout(() => URL.revokeObjectURL(url), 1000)
      setDone(true)
    } catch (caught) { setError((caught as Error).message) }
    finally { setBusy(false) }
  }

  return <div className="account-form">
    <h3>Download my data</h3>
    <p className="case-help">A JSON file of the account information ECHOTRACE stores for you, generated by the server when you click.</p>
    <div className="account-form-footer">
      <p className={error ? 'account-error' : 'account-status'} role={error ? 'alert' : 'status'}>{error || (done ? 'Download started.' : '')}</p>
      <button type="button" className="outline-button" onClick={download} disabled={busy}>{busy ? <LoaderCircle size={15} className="spin" /> : <ArrowDownToLine size={15} />}{busy ? 'Preparing…' : 'Download my data'}</button>
    </div>
  </div>
}

export default function AccountSettings({ preferences, onPreferencesChange, onRecordingsDeleted }: Props) {
  const [saving, setSaving] = useState<PreferenceKey | null>(null)
  const [errors, setErrors] = useState<Partial<Record<PreferenceKey, string>>>({})

  async function update<K extends PreferenceKey>(key: K, value: Preferences[K]) {
    setSaving(key); setErrors(current => ({ ...current, [key]: undefined }))
    try {
      const response = await sendJson<{ preferences: Preferences }>('/api/account/preferences', 'PATCH', { [key]: value })
      onPreferencesChange(response.preferences)
    } catch (caught) { setErrors(current => ({ ...current, [key]: `Not saved: ${(caught as Error).message}` })) }
    finally { setSaving(null) }
  }

  async function deleteRecordings() {
    const { deleted } = await sendJson<{ deleted: number }>('/api/account/recordings/delete', 'POST', { confirm: CONFIRM_WORD })
    onRecordingsDeleted()
    return `Deleted ${deleted} ${deleted === 1 ? 'recording' : 'recordings'}.`
  }
  async function deleteAccount() {
    await sendJson('/api/account/delete', 'POST', { confirm: CONFIRM_WORD })
    goTo('/')
  }

  return <div className="account-grid">
    <GlassEffect as="section" className="detail-section account-card" aria-labelledby="account-preferences-heading">
      <div className="section-heading"><div><span className="eyebrow">PREFERENCES</span><h2 id="account-preferences-heading">Workspace</h2></div></div>
      {!preferences ? <p className="case-help" role="status">Loading your preferences…</p> : <>
        <PreferenceSelect id="default_view" label="Open the app in" help="The view shown when you first open ECHOTRACE." value={preferences.default_view} busy={saving === 'default_view'} error={errors.default_view}
          options={[{ value: 'investigation', label: 'Investigation' }, { value: 'batch', label: 'Batch & export' }]} onChange={value => update('default_view', value as Preferences['default_view'])} />
        <PreferenceSelect id="time_format" label="Time format" help="Used for dates and times in lists and reports on screen." value={preferences.time_format} busy={saving === 'time_format'} error={errors.time_format}
          options={[{ value: '12h', label: '12-hour (2:30 PM)' }, { value: '24h', label: '24-hour (14:30)' }]} onChange={value => update('time_format', value as Preferences['time_format'])} />
        <PreferenceSelect id="motion" label="Motion" help="Reduce turns off interface animations and transitions, whatever your device setting." value={preferences.motion} busy={saving === 'motion'} error={errors.motion}
          options={[{ value: 'system', label: 'Follow device setting' }, { value: 'reduce', label: 'Reduce motion' }]} onChange={value => update('motion', value as Preferences['motion'])} />
      </>}
    </GlassEffect>
    <GlassEffect as="section" className="detail-section account-card" aria-labelledby="account-privacy-heading">
      <div className="section-heading"><div><span className="eyebrow">PRIVACY</span><h2 id="account-privacy-heading">AI interpretation</h2></div></div>
      {!preferences ? <p className="case-help" role="status">Loading your preferences…</p> : <div className="account-preference">
        <label className="account-toggle">
          <input type="checkbox" checked={preferences.ai_interpretation} disabled={saving === 'ai_interpretation'} aria-describedby="pref-ai-note" onChange={event => update('ai_interpretation', event.target.checked)} />
          <span>Allow AI interpretation</span>
        </label>
        <p id="pref-ai-note" className="case-help">When you ask for an interpretation, ECHOTRACE sends only measured numbers from the analysis to Groq. Your audio, filenames and transcripts are never sent. When this is off, interpretation requests are refused and nothing is sent to Groq.</p>
        <p className={errors.ai_interpretation ? 'account-error' : 'account-status'} role={errors.ai_interpretation ? 'alert' : 'status'}>{saving === 'ai_interpretation' ? 'Saving…' : errors.ai_interpretation || ''}</p>
      </div>}
    </GlassEffect>
    <GlassEffect as="section" className="detail-section account-card" aria-labelledby="account-data-heading">
      <div className="section-heading"><div><span className="eyebrow">YOUR DATA</span><h2 id="account-data-heading">Export and remove</h2></div></div>
      <DownloadData />
      <div className="account-divider" />
      <TypedConfirm title="Delete all recordings" description="Removes every recording you added, with its analyses, reviews and reports. Your account stays open. This cannot be undone."
        buttonLabel="Delete all recordings" busyLabel="Deleting…" onConfirm={deleteRecordings} />
    </GlassEffect>
    <GlassEffect as="section" className="detail-section account-card account-danger" aria-labelledby="account-danger-heading">
      <div className="section-heading"><div><span className="eyebrow">DANGER ZONE</span><h2 id="account-danger-heading">Delete account</h2></div></div>
      <TypedConfirm title="Delete my account" description="Permanently removes your account, all recordings, analyses and reports, and signs you out everywhere. This cannot be undone."
        buttonLabel="Delete account" busyLabel="Deleting account…" onConfirm={deleteAccount} />
    </GlassEffect>
  </div>
}
