import { useEffect, useState } from 'react'
import { Save, RefreshCw } from 'lucide-react'
import { InfoButton } from './ui/info-button'
type Review={status:string;notes:string;version:number;updated_at?:string|null}
async function request(url:string,init?:RequestInit):Promise<Review>{const r=await fetch(url,init);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Review changed or could not be saved. Refresh the saved version before trying again.');return data}
function Form({jobId,onSaved}:{jobId:string;onSaved:()=>void}){
 const [review,setReview]=useState<Review|null>(null);const [status,setStatus]=useState('needs_review');const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const [refresh,setRefresh]=useState(0)
 const endpoint=`/api/analyses/${encodeURIComponent(jobId)}/analyst-review`;const draftKey=`echotrace-review-draft-${jobId}`
 useEffect(()=>{let live=true;setError('');request(endpoint).then(data=>{if(!live)return;setReview(data);let draft:null|{status:string;notes:string}=null;try{draft=JSON.parse(sessionStorage.getItem(draftKey)||'null')}catch{/* unavailable storage */}setStatus(draft?.status||data.status);setNotes(draft?.notes??data.notes)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[endpoint,refresh,draftKey])
 function draft(nextStatus:string,nextNotes:string){setSaved(false);setStatus(nextStatus);setNotes(nextNotes);try{sessionStorage.setItem(draftKey,JSON.stringify({status:nextStatus,notes:nextNotes}))}catch{/* form remains usable */}}
 async function save(){if(!review)return;setBusy(true);setError('');try{const data=await request(endpoint,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,notes,expected_version:review.version})});setReview(data);setSaved(true);try{sessionStorage.removeItem(draftKey)}catch{/* optional local draft */}onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save review.')}finally{setBusy(false)}}
 return <section className="detail-section case-panel analyst-panel" aria-label="Analyst disposition"><div className="section-heading"><div><span className="eyebrow">YOUR REVIEW</span><h2>Record the next step</h2></div><InfoButton label="Analyst review">Your judgment is stored separately from model output. Review complete means you finished your review; it does not certify a recording as authentic. Unsaved drafts stay in this browser tab.</InfoButton></div>
 {error&&<p role="alert" className="case-error">{error}<button className="text-button" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={14}/> Refresh saved version; keep draft</button></p>}
 {!review&&!error&&<p role="status" className="case-help">Loading saved review…</p>}
 {review&&<><div className="analyst-fields"><label className="case-field">Review status<select value={status} onChange={e=>draft(e.target.value,notes)} disabled={busy}><option value="needs_review">Needs review</option><option value="corroboration_requested">Corroboration requested</option><option value="review_complete">Review complete</option></select></label><label className="case-field">Analyst notes<textarea rows={4} maxLength={8000} placeholder="What did you observe? What should the next reviewer check?" value={notes} disabled={busy} onChange={e=>draft(status,e.target.value)}/></label></div><div className="analyst-footer"><p>{saved?<span role="status">Review saved.</span>:review.version?`Saved version ${review.version} · edit and save to update.`:'No analyst judgment recorded yet.'}</p><button className="primary-button" onClick={save} disabled={busy}><Save size={16}/>{busy?'Saving…':'Save review'}</button></div></>}
 </section>
}
export default function AnalystReview(props:{jobId:string;onSaved:()=>void}){return <Form key={props.jobId} {...props}/>}
