import { useEffect, useState } from 'react'
type Metrics = { recall: number; false_positive_rate: number; roc_auc: number }
type Evaluation = { scope: string; serving_model: string; experiments: {name: string; promoted: boolean; reason: string; sample_count: number; baseline: Metrics; candidate: Metrics}[] }
export default function ModelValidation() {
  const [data, setData] = useState<Evaluation | null>(null)
  const [error, setError] = useState(false)
  useEffect(() => { const controller = new AbortController(); fetch('/api/model/evaluation', { signal: controller.signal }).then(r => { if (!r.ok) throw Error(); return r.json() }).then(setData).catch(() => { if (!controller.signal.aborted) setError(true) }); return () => controller.abort() }, [])
  return <details className="model-validation detail-section case-panel"><summary>Detector validation · measured performance</summary>{error ? <p className="case-help">Validation summary could not be loaded. Refresh to retry.</p> : !data ? <p className="case-help">Loading validation…</p> : <><p className="case-help">Serving: {data.serving_model}. {data.scope}</p>{data.experiments.map(experiment => <section key={experiment.name}><h3>{experiment.name}</h3><p className="case-help">{experiment.promoted ? 'Promoted after evaluation' : 'Experimental · not serving'} · {experiment.sample_count.toLocaleString()} independent recordings</p><div className="table-scroll"><table><thead><tr><th>Metric</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody><tr><td>Synthetic recordings caught</td><td>{(experiment.baseline.recall*100).toFixed(1)}%</td><td>{(experiment.candidate.recall*100).toFixed(1)}%</td></tr><tr><td>Genuine recordings falsely flagged</td><td>{(experiment.baseline.false_positive_rate*100).toFixed(1)}%</td><td>{(experiment.candidate.false_positive_rate*100).toFixed(1)}%</td></tr><tr><td>AUROC</td><td>{experiment.baseline.roc_auc.toFixed(3)}</td><td>{experiment.candidate.roc_auc.toFixed(3)}</td></tr></tbody></table></div><p className="case-help">{experiment.reason}</p></section>)}</>}</details>
}
